-- Seed standard training guides

-- 1. Couch to 5K (8 weeks, beginner)
INSERT INTO public.standard_guides (title, description, category, duration_weeks, sessions) VALUES (
  'Couch to 5K',
  'Perfect for absolute beginners. This 8-week program gradually builds your endurance through a combination of walking and running, preparing you to run a full 5K.',
  'beginner',
  8,
  '[
    {"week": 1, "day": 1, "type": "Intervals", "description": "Alternate 60 seconds of jogging with 90 seconds of walking for 20 minutes", "duration": 1200},
    {"week": 1, "day": 2, "type": "Intervals", "description": "Alternate 60 seconds of jogging with 90 seconds of walking for 20 minutes", "duration": 1200},
    {"week": 1, "day": 3, "type": "Intervals", "description": "Alternate 60 seconds of jogging with 90 seconds of walking for 20 minutes", "duration": 1200},
    {"week": 2, "day": 1, "type": "Intervals", "description": "Alternate 90 seconds of jogging with 2 minutes of walking for 20 minutes", "duration": 1200},
    {"week": 2, "day": 2, "type": "Intervals", "description": "Alternate 90 seconds of jogging with 2 minutes of walking for 20 minutes", "duration": 1200},
    {"week": 2, "day": 3, "type": "Intervals", "description": "Alternate 90 seconds of jogging with 2 minutes of walking for 20 minutes", "duration": 1200},
    {"week": 3, "day": 1, "type": "Intervals", "description": "Run 3 minutes, walk 90 seconds, repeat for 20 minutes", "duration": 1200},
    {"week": 3, "day": 2, "type": "Intervals", "description": "Run 3 minutes, walk 90 seconds, repeat for 20 minutes", "duration": 1200},
    {"week": 3, "day": 3, "type": "Intervals", "description": "Run 3 minutes, walk 90 seconds, repeat for 20 minutes", "duration": 1200},
    {"week": 4, "day": 1, "type": "Intervals", "description": "Run 5 minutes, walk 2 minutes, repeat 3 times", "duration": 1500},
    {"week": 4, "day": 2, "type": "Intervals", "description": "Run 5 minutes, walk 2 minutes, repeat 3 times", "duration": 1500},
    {"week": 4, "day": 3, "type": "Intervals", "description": "Run 5 minutes, walk 2 minutes, repeat 3 times", "duration": 1500},
    {"week": 5, "day": 1, "type": "Run", "description": "Run 10 minutes, walk 3 minutes, run 10 minutes", "duration": 1380},
    {"week": 5, "day": 2, "type": "Run", "description": "Run 10 minutes, walk 3 minutes, run 10 minutes", "duration": 1380},
    {"week": 5, "day": 3, "type": "Run", "description": "Run 10 minutes, walk 3 minutes, run 10 minutes", "duration": 1380},
    {"week": 6, "day": 1, "type": "Run", "description": "Run 15 minutes, walk 2 minutes, run 15 minutes", "duration": 1920},
    {"week": 6, "day": 2, "type": "Run", "description": "Run 15 minutes, walk 2 minutes, run 15 minutes", "duration": 1920},
    {"week": 6, "day": 3, "type": "Run", "description": "Run 15 minutes, walk 2 minutes, run 15 minutes", "duration": 1920},
    {"week": 7, "day": 1, "type": "Run", "description": "Run 25 minutes continuously", "duration": 1500},
    {"week": 7, "day": 2, "type": "Run", "description": "Run 25 minutes continuously", "duration": 1500},
    {"week": 7, "day": 3, "type": "Run", "description": "Run 25 minutes continuously", "duration": 1500},
    {"week": 8, "day": 1, "type": "Run", "description": "Run 28 minutes continuously", "duration": 1680},
    {"week": 8, "day": 2, "type": "Run", "description": "Run 30 minutes continuously", "duration": 1800},
    {"week": 8, "day": 3, "type": "5K Race", "description": "Complete your first 5K! Run at a comfortable pace", "distance": 5}
  ]'::jsonb
);

-- 2. 10K Training Plan (10 weeks, intermediate)
INSERT INTO public.standard_guides (title, description, category, duration_weeks, sessions) VALUES (
  '10K Training Plan',
  'For runners who can comfortably run 5K and want to step up to 10K. This 10-week program builds endurance and speed over 4 runs per week.',
  'distance',
  10,
  '[
    {"week": 1, "day": 1, "type": "Easy Run", "description": "Easy pace run", "distance": 5},
    {"week": 1, "day": 2, "type": "Tempo Run", "description": "15 min easy, 15 min tempo, 10 min easy", "duration": 2400},
    {"week": 1, "day": 3, "type": "Easy Run", "description": "Recovery run at comfortable pace", "distance": 4},
    {"week": 1, "day": 4, "type": "Long Run", "description": "Slow and steady pace", "distance": 6},
    {"week": 2, "day": 1, "type": "Easy Run", "description": "Easy pace run", "distance": 5},
    {"week": 2, "day": 2, "type": "Intervals", "description": "5 x 800m at 10K pace with 2 min recovery", "distance": 6},
    {"week": 2, "day": 3, "type": "Easy Run", "description": "Recovery run", "distance": 4},
    {"week": 2, "day": 4, "type": "Long Run", "description": "Increase distance gradually", "distance": 7},
    {"week": 3, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 5},
    {"week": 3, "day": 2, "type": "Tempo Run", "description": "20 min tempo pace", "distance": 6},
    {"week": 3, "day": 3, "type": "Easy Run", "description": "Recovery run", "distance": 4},
    {"week": 3, "day": 4, "type": "Long Run", "description": "Build endurance", "distance": 8},
    {"week": 4, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 5},
    {"week": 4, "day": 2, "type": "Intervals", "description": "6 x 800m at 10K pace", "distance": 7},
    {"week": 4, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 4},
    {"week": 4, "day": 4, "type": "Long Run", "description": "Steady pace", "distance": 9},
    {"week": 5, "day": 1, "type": "Easy Run", "description": "Comfortable run", "distance": 6},
    {"week": 5, "day": 2, "type": "Tempo Run", "description": "25 min tempo pace", "distance": 7},
    {"week": 5, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 5, "day": 4, "type": "Long Run", "description": "Peak distance week", "distance": 10},
    {"week": 6, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 5},
    {"week": 6, "day": 2, "type": "Intervals", "description": "4 x 1200m at 10K pace", "distance": 7},
    {"week": 6, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 4},
    {"week": 6, "day": 4, "type": "Long Run", "description": "Maintain endurance", "distance": 9},
    {"week": 7, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 6},
    {"week": 7, "day": 2, "type": "Tempo Run", "description": "30 min tempo", "distance": 8},
    {"week": 7, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 7, "day": 4, "type": "Long Run", "description": "Build confidence", "distance": 11},
    {"week": 8, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 6},
    {"week": 8, "day": 2, "type": "Intervals", "description": "5 x 1000m at 10K pace", "distance": 8},
    {"week": 8, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 4},
    {"week": 8, "day": 4, "type": "Long Run", "description": "Peak long run", "distance": 12},
    {"week": 9, "day": 1, "type": "Easy Run", "description": "Start tapering", "distance": 5},
    {"week": 9, "day": 2, "type": "Tempo Run", "description": "20 min tempo", "distance": 6},
    {"week": 9, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 4},
    {"week": 9, "day": 4, "type": "Long Run", "description": "Reduce volume", "distance": 8},
    {"week": 10, "day": 1, "type": "Easy Run", "description": "Light run", "distance": 4},
    {"week": 10, "day": 2, "type": "Easy Run", "description": "Very easy shake-out", "distance": 3},
    {"week": 10, "day": 3, "type": "Rest", "description": "Rest before race"},
    {"week": 10, "day": 4, "type": "10K Race", "description": "Race day! Run your best 10K", "distance": 10}
  ]'::jsonb
);

-- 3. Half Marathon Prep (12 weeks, intermediate)
INSERT INTO public.standard_guides (title, description, category, duration_weeks, sessions) VALUES (
  'Half Marathon Prep',
  'Designed for runners comfortable with 10K who want to tackle the half marathon distance. 12 weeks of progressive training with 4-5 runs per week.',
  'distance',
  12,
  '[
    {"week": 1, "day": 1, "type": "Easy Run", "description": "Easy pace to start", "distance": 5},
    {"week": 1, "day": 2, "type": "Tempo Run", "description": "20 min tempo effort", "distance": 6},
    {"week": 1, "day": 3, "type": "Easy Run", "description": "Recovery run", "distance": 4},
    {"week": 1, "day": 4, "type": "Long Run", "description": "Build base", "distance": 10},
    {"week": 2, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 6},
    {"week": 2, "day": 2, "type": "Intervals", "description": "6 x 800m at half marathon pace", "distance": 8},
    {"week": 2, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 2, "day": 4, "type": "Long Run", "description": "Increase distance", "distance": 11},
    {"week": 3, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 6},
    {"week": 3, "day": 2, "type": "Tempo Run", "description": "25 min tempo", "distance": 7},
    {"week": 3, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 3, "day": 4, "type": "Long Run", "description": "Progressive build", "distance": 12},
    {"week": 4, "day": 1, "type": "Easy Run", "description": "Comfortable run", "distance": 7},
    {"week": 4, "day": 2, "type": "Intervals", "description": "5 x 1200m at HM pace", "distance": 9},
    {"week": 4, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 4, "day": 4, "type": "Long Run", "description": "Building endurance", "distance": 13},
    {"week": 5, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 7},
    {"week": 5, "day": 2, "type": "Tempo Run", "description": "30 min tempo", "distance": 8},
    {"week": 5, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 6},
    {"week": 5, "day": 4, "type": "Long Run", "description": "Continue building", "distance": 14},
    {"week": 6, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 8},
    {"week": 6, "day": 2, "type": "Intervals", "description": "4 x 1600m at HM pace", "distance": 10},
    {"week": 6, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 6},
    {"week": 6, "day": 4, "type": "Long Run", "description": "Peak building phase", "distance": 15},
    {"week": 7, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 8},
    {"week": 7, "day": 2, "type": "Tempo Run", "description": "35 min tempo", "distance": 9},
    {"week": 7, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 6},
    {"week": 7, "day": 4, "type": "Long Run", "description": "Longest run approaches", "distance": 16},
    {"week": 8, "day": 1, "type": "Easy Run", "description": "Comfortable run", "distance": 8},
    {"week": 8, "day": 2, "type": "Intervals", "description": "6 x 1200m at HM pace", "distance": 10},
    {"week": 8, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 7},
    {"week": 8, "day": 4, "type": "Long Run", "description": "Peak long run", "distance": 18},
    {"week": 9, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 7},
    {"week": 9, "day": 2, "type": "Tempo Run", "description": "30 min tempo", "distance": 8},
    {"week": 9, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 6},
    {"week": 9, "day": 4, "type": "Long Run", "description": "Maintain endurance", "distance": 16},
    {"week": 10, "day": 1, "type": "Easy Run", "description": "Start taper", "distance": 6},
    {"week": 10, "day": 2, "type": "Intervals", "description": "4 x 1000m at HM pace", "distance": 8},
    {"week": 10, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 10, "day": 4, "type": "Long Run", "description": "Reduce volume", "distance": 12},
    {"week": 11, "day": 1, "type": "Easy Run", "description": "Taper continues", "distance": 5},
    {"week": 11, "day": 2, "type": "Tempo Run", "description": "20 min tempo", "distance": 6},
    {"week": 11, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 4},
    {"week": 11, "day": 4, "type": "Easy Run", "description": "Short long run", "distance": 8},
    {"week": 12, "day": 1, "type": "Easy Run", "description": "Light run", "distance": 4},
    {"week": 12, "day": 2, "type": "Easy Run", "description": "Very easy", "distance": 3},
    {"week": 12, "day": 3, "type": "Rest", "description": "Rest before race"},
    {"week": 12, "day": 4, "type": "Half Marathon Race", "description": "Race day! Enjoy your half marathon", "distance": 21.1}
  ]'::jsonb
);

-- 4. Marathon Training (16 weeks, advanced)
INSERT INTO public.standard_guides (title, description, category, duration_weeks, sessions) VALUES (
  'Marathon Training',
  'Comprehensive 16-week marathon training plan for runners with a solid running base. Includes 4-5 runs per week with progressive mileage build-up.',
  'distance',
  16,
  '[
    {"week": 1, "day": 1, "type": "Easy Run", "description": "Foundation building", "distance": 8},
    {"week": 1, "day": 2, "type": "Tempo Run", "description": "25 min tempo", "distance": 10},
    {"week": 1, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 6},
    {"week": 1, "day": 4, "type": "Long Run", "description": "Base mileage", "distance": 16},
    {"week": 2, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 8},
    {"week": 2, "day": 2, "type": "Intervals", "description": "8 x 800m at marathon pace", "distance": 11},
    {"week": 2, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 7},
    {"week": 2, "day": 4, "type": "Long Run", "description": "Build endurance", "distance": 18},
    {"week": 3, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 9},
    {"week": 3, "day": 2, "type": "Tempo Run", "description": "30 min tempo", "distance": 11},
    {"week": 3, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 7},
    {"week": 3, "day": 4, "type": "Long Run", "description": "Progressive build", "distance": 20},
    {"week": 4, "day": 1, "type": "Easy Run", "description": "Recovery week", "distance": 7},
    {"week": 4, "day": 2, "type": "Easy Run", "description": "Light effort", "distance": 8},
    {"week": 4, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 6},
    {"week": 4, "day": 4, "type": "Long Run", "description": "Reduced volume", "distance": 16},
    {"week": 5, "day": 1, "type": "Easy Run", "description": "Back to building", "distance": 9},
    {"week": 5, "day": 2, "type": "Intervals", "description": "6 x 1200m at MP", "distance": 12},
    {"week": 5, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 8},
    {"week": 5, "day": 4, "type": "Long Run", "description": "Increase distance", "distance": 22},
    {"week": 6, "day": 1, "type": "Easy Run", "description": "Comfortable run", "distance": 10},
    {"week": 6, "day": 2, "type": "Tempo Run", "description": "35 min tempo", "distance": 12},
    {"week": 6, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 8},
    {"week": 6, "day": 4, "type": "Long Run", "description": "Build continues", "distance": 24},
    {"week": 7, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 10},
    {"week": 7, "day": 2, "type": "Intervals", "description": "5 x 1600m at MP", "distance": 13},
    {"week": 7, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 8},
    {"week": 7, "day": 4, "type": "Long Run", "description": "Approaching peak", "distance": 26},
    {"week": 8, "day": 1, "type": "Easy Run", "description": "Recovery week", "distance": 8},
    {"week": 8, "day": 2, "type": "Tempo Run", "description": "25 min tempo", "distance": 10},
    {"week": 8, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 7},
    {"week": 8, "day": 4, "type": "Long Run", "description": "Reduced", "distance": 20},
    {"week": 9, "day": 1, "type": "Easy Run", "description": "Build resumes", "distance": 11},
    {"week": 9, "day": 2, "type": "Intervals", "description": "8 x 1000m at MP", "distance": 14},
    {"week": 9, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 9},
    {"week": 9, "day": 4, "type": "Long Run", "description": "Long run peak approaching", "distance": 28},
    {"week": 10, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 11},
    {"week": 10, "day": 2, "type": "Tempo Run", "description": "40 min tempo", "distance": 14},
    {"week": 10, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 9},
    {"week": 10, "day": 4, "type": "Long Run", "description": "Peak long run", "distance": 32},
    {"week": 11, "day": 1, "type": "Easy Run", "description": "Easy run", "distance": 10},
    {"week": 11, "day": 2, "type": "Intervals", "description": "6 x 1200m at MP", "distance": 13},
    {"week": 11, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 8},
    {"week": 11, "day": 4, "type": "Long Run", "description": "Maintain endurance", "distance": 28},
    {"week": 12, "day": 1, "type": "Easy Run", "description": "Recovery week", "distance": 9},
    {"week": 12, "day": 2, "type": "Tempo Run", "description": "30 min tempo", "distance": 11},
    {"week": 12, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 7},
    {"week": 12, "day": 4, "type": "Long Run", "description": "Reduced volume", "distance": 22},
    {"week": 13, "day": 1, "type": "Easy Run", "description": "Final build week", "distance": 10},
    {"week": 13, "day": 2, "type": "Intervals", "description": "5 x 1600m at MP", "distance": 13},
    {"week": 13, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 8},
    {"week": 13, "day": 4, "type": "Long Run", "description": "Last long run", "distance": 24},
    {"week": 14, "day": 1, "type": "Easy Run", "description": "Taper begins", "distance": 8},
    {"week": 14, "day": 2, "type": "Tempo Run", "description": "25 min tempo", "distance": 10},
    {"week": 14, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 6},
    {"week": 14, "day": 4, "type": "Long Run", "description": "Reduce mileage", "distance": 16},
    {"week": 15, "day": 1, "type": "Easy Run", "description": "Taper continues", "distance": 6},
    {"week": 15, "day": 2, "type": "Easy Run", "description": "Light run", "distance": 8},
    {"week": 15, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 15, "day": 4, "type": "Easy Run", "description": "Short long run", "distance": 12},
    {"week": 16, "day": 1, "type": "Easy Run", "description": "Very light", "distance": 5},
    {"week": 16, "day": 2, "type": "Easy Run", "description": "Shake-out run", "distance": 3},
    {"week": 16, "day": 3, "type": "Rest", "description": "Complete rest"},
    {"week": 16, "day": 4, "type": "Marathon Race", "description": "Marathon race day! Trust your training", "distance": 42.2}
  ]'::jsonb
);

-- 5. Speed & Interval Training (6 weeks, all levels)
INSERT INTO public.standard_guides (title, description, category, duration_weeks, sessions) VALUES (
  'Speed & Interval Training',
  'A 6-week program focused on improving your speed and running economy through interval training, tempo runs, and speed work. Suitable for all levels.',
  'speed',
  6,
  '[
    {"week": 1, "day": 1, "type": "Easy Run", "description": "Warm-up week", "distance": 5},
    {"week": 1, "day": 2, "type": "Intervals", "description": "6 x 400m at 5K pace with 90 sec recovery", "distance": 6},
    {"week": 1, "day": 3, "type": "Easy Run", "description": "Recovery run", "distance": 4},
    {"week": 1, "day": 4, "type": "Tempo Run", "description": "20 min tempo effort", "distance": 6},
    {"week": 2, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 5},
    {"week": 2, "day": 2, "type": "Intervals", "description": "8 x 400m at 5K pace with 90 sec recovery", "distance": 7},
    {"week": 2, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 4},
    {"week": 2, "day": 4, "type": "Fartlek", "description": "30 min fartlek (1 min fast, 2 min easy)", "distance": 7},
    {"week": 3, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 6},
    {"week": 3, "day": 2, "type": "Intervals", "description": "5 x 800m at 5K pace with 2 min recovery", "distance": 8},
    {"week": 3, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 3, "day": 4, "type": "Tempo Run", "description": "25 min tempo", "distance": 7},
    {"week": 4, "day": 1, "type": "Easy Run", "description": "Comfortable run", "distance": 6},
    {"week": 4, "day": 2, "type": "Intervals", "description": "4 x 1200m at 10K pace with 2 min recovery", "distance": 9},
    {"week": 4, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 4, "day": 4, "type": "Hill Repeats", "description": "8 x 60 sec hill sprints with jog down recovery", "distance": 7},
    {"week": 5, "day": 1, "type": "Easy Run", "description": "Easy pace", "distance": 6},
    {"week": 5, "day": 2, "type": "Intervals", "description": "6 x 800m at 5K pace with 90 sec recovery", "distance": 9},
    {"week": 5, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 5},
    {"week": 5, "day": 4, "type": "Tempo Run", "description": "30 min tempo", "distance": 8},
    {"week": 6, "day": 1, "type": "Easy Run", "description": "Comfortable pace", "distance": 5},
    {"week": 6, "day": 2, "type": "Intervals", "description": "3 x 1600m at 5K pace with 3 min recovery", "distance": 10},
    {"week": 6, "day": 3, "type": "Easy Run", "description": "Recovery", "distance": 4},
    {"week": 6, "day": 4, "type": "Time Trial", "description": "5K time trial to test your speed gains!", "distance": 5}
  ]'::jsonb
);
